export const FETCH_POSTS = 'FETCH_POSTS'
export const NEW_POST = 'NEW_POST'

export const FETCH_QUESTIONS = 'FETCH_QUESTIONS'

export const NEW_TEST_RESULT = 'NEW_TEST_RESULT'
export const UPDATE_TEST_RESULT = 'UPDATE_TEST_RESULT'

export const NEW_FEEDBACK = 'NEW_FEEDBACK'

export const FETCH_IDEOLOGIES = 'FETCH_IDEOLOGIES'

export const CLEAR_DATA = 'CLEAR_DATA'

